// Generated by https://pagedraw.io/pages/9921
import React from "react";
import styled, { injectGlobal } from "styled-components";
import "./header.css";
injectGlobal`
    @import url('https://fonts.googleapis.com/css?family=Nunito:600|Nunito:|Open+Sans:');
    
    * {
        box-sizing: border-box;
    }
    
    body {
        margin: 0;
    }
    
    button:hover {
        cursor: pointer;
    }
    
    a {
        text-decoration: none;
        color: inherit;
    }
    
    .pd-onhover-parent >.pd-onhover {
        display: none;
    }
    
    .pd-onhover-parent:hover > * {
        display: none;
    }
    
    .pd-onhover-parent:hover > .pd-onhover {
        display: flex;
    }
    
    .pd-onactive-parent > .pd-onactive {
        display: none;
    }
    
    .pd-onactive-parent:active > * {
        display: none;
    }
    
    .pd-onactive-parent:active > .pd-onactive {
        display: flex;
    }
    
    .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
        display: none;
    }
`;
const Header_header_7 = styled.div`
  display: flex;
  flex-direction: column;
  flex-grow: 1;
`;

const Header_0 = styled.div`
  display: flex;
`;

const Header_image_8 = styled.div`
  display: flex;
  flex-direction: column;
  background-image: url("https://s3-us-west-2.amazonaws.com/figma-alpha/img/6e64/c6a7/149da0b376dd56c1ec8d0af7c27b4fd0");
  background-size: 100% 100%;
`;

const Header_0_0_0 = styled.div`
  display: flex;
  padding-left: 35px;
`;

const Header_background_0 = styled.div`
  display: flex;
  flex-direction: column;
  padding-top: 40px;
  padding-bottom: 92px;
  background: rgba(0, 0, 0, 0.699999988079071);
`;

const Header_0_0_0_0_0 = styled.div`
  display: flex;
  padding-left: 645px;
  padding-right: 646px;
`;

const Header_logo_0 = styled.div`
  display: flex;
  flex-direction: column;
  padding-top: 6px;
  padding-bottom: 7px;
  background: rgba(NaN, NaN, NaN, 0);
  border: 2px solid rgba(255, 255, 255, 1);
`;

const Header_0_0_0_0_0_0_0 = styled.div`
  display: flex;
`;

const Header_text_0 = styled.div`
  width: 145px;
  flex-shrink: 0;
  font-family: "Nunito", sans-serif;
  color: rgba(255, 255, 255, 1);
  font-size: 30px;
  line-height: 34px;
  letter-spacing: 0px;
  font-weight: 600;
  font-style: normal;
  text-decoration: none;
  text-align: center;
  word-wrap: break-word;
`;

const Header_0_0_0_0_1 = styled.div`
  display: flex;
  margin-top: 157px;
  padding-left: 386px;
  padding-right: 385px;
`;

const Header_heading_0 = styled.div`
  width: 669px;
  flex-shrink: 0;
  font-family: "Nunito", sans-serif;
  color: rgba(255, 255, 255, 1);
  font-size: 53px;
  line-height: 60px;
  letter-spacing: 0px;
  font-weight: bold;
  font-style: normal;
  text-decoration: none;
  text-align: CENTER;
  word-wrap: break-word;
`;

const Header_0_0_0_0_2 = styled.div`
  display: flex;
  margin-top: 26px;
  padding-left: 321px;
  padding-right: 321px;
`;

const Header_paragraph_0 = styled.div`
  width: 798px;
  flex-shrink: 0;
  font-family: "Open Sans", sans-serif;
  color: rgba(255, 255, 255, 1);
  font-size: 25px;
  line-height: 28px;
  letter-spacing: 0px;
  font-weight: normal;
  font-style: normal;
  text-decoration: none;
  text-align: LEFT;
  word-wrap: break-word;
`;

const Header_0_0_0_0_3 = styled.div`
  display: flex;
  margin-top: 169px;
  padding-left: 572px;
  padding-right: 543px;
`;

const Header_down_button_0 = styled.div`
  display: flex;
  flex-direction: column;
  padding-top: 19px;
  padding-bottom: 7px;
  border-radius: 50px;
  background: rgba(45, 156, 219, 1);
`;

const Header_0_0_0_0_3_0_0 = styled.div`
  display: flex;
  padding-left: 2px;
`;

const Header_0_0_0_0_3_0_0_0 = styled.div`
  width: 323px;
  height: 78px;
  flex-shrink: 0;
  position: relative;
`;

const Header_button_text_0 = styled.div`
  width: 323px;
  flex-grow: 1;
  position: absolute;
  top: 0px;
  left: 0px;
  font-family: "Nunito", sans-serif;
  color: rgba(255, 255, 255, 1);
  font-size: 30px;
  line-height: 34px;
  letter-spacing: 0px;
  font-weight: bold;
  font-style: normal;
  text-decoration: none;
  text-align: center;
  word-wrap: break-word;
`;

const Header_chevron_down_3 = styled.img`
  width: 48px;
  height: 48px;
  flex-grow: 1;
  position: absolute;
  top: 30px;
  left: 137px;
  border-width: 0px;
`;
function render() {
  return (
    <Header_header_7>
      <Header_0>
        <Header_image_8>
          <Header_0_0_0>
            <Header_background_0>
              <Header_0_0_0_0_0>
                <Header_logo_0>
                  <Header_0_0_0_0_0_0_0>
                    <Header_text_0>SELA</Header_text_0>
                  </Header_0_0_0_0_0_0_0>
                </Header_logo_0>
              </Header_0_0_0_0_0>
              <Header_0_0_0_0_1>
                <Header_heading_0>
                  <div>Keep track of development </div>
                  <div>projects near you</div>
                </Header_heading_0>
              </Header_0_0_0_0_1>
              <Header_0_0_0_0_2>
                <Header_paragraph_0>
                  <div>
                    The Sela Platform enables stakeholders share real time
                    information
                  </div>
                  <div>
                    on the state of infrastructure projects to ensure
                    transparent delivery
                  </div>
                </Header_paragraph_0>
              </Header_0_0_0_0_2>
              <Header_0_0_0_0_3>
                <Header_down_button_0>
                  <Header_0_0_0_0_3_0_0>
                    <Header_0_0_0_0_3_0_0_0>
                      <Header_button_text_0>SEE PROJECTS</Header_button_text_0>
                      <Header_chevron_down_3 src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/1674/e3d9/09124a4ac716dcd218718ada4b6b6428" />
                    </Header_0_0_0_0_3_0_0_0>
                  </Header_0_0_0_0_3_0_0>
                </Header_down_button_0>
              </Header_0_0_0_0_3>
            </Header_background_0>
          </Header_0_0_0>
        </Header_image_8>
      </Header_0>
    </Header_header_7>
  );
}

export default function(props) {
  return render.apply({ props: props });
}
