// Generated by https://pagedraw.io/pages/9910
import React from 'react';
import './sela_platform.css';

function render() {
    return <div className="sela_platform-sela_platform-0">
        <div className="sela_platform-0">
            <div className="sela_platform-card-0">
                <div className="sela_platform-0-0-0">
                    <div className="sela_platform-image-7">
                        <div className="sela_platform-0-0-0-0-0">
                            <div className="sela_platform-image_mask-0">
                                <div className="sela_platform-0-0-0-0-0-0-0">
                                    <div className="sela_platform-0-0-0-0-0-0-0-0">
                                        <div className="sela_platform-0-0-0-0-0-0-0-0-0">
                                            <div className="sela_platform-0-0-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-rectangle_4" /> 
                                                <div className="sela_platform-initiated-0">Initiated</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-0-0-0-0-0-0-1">
                                    <div className="sela_platform-0-0-0-0-0-0-1-0">
                                        <div className="sela_platform-0-0-0-0-0-0-1-0-0">
                                            <div className="sela_platform-0-0-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_bar-0">
                                                    <div className="sela_platform-0-0-0-0-0-0-1-0-0-0-0-0">
                                                        <div className="sela_platform-progress_indicator-0" /> 
                                                    </div>
                                                </div>
                                                <div className="sela_platform-20">{"20% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-0-0-0-1">
                        <div className="sela_platform-0-0-0-1-0">
                            <div className="sela_platform-0-0-0-1-0-0">
                                <div className="sela_platform-0-0-0-1-0-0-0">
                                    <div className="sela_platform-0-0-0-1-0-0-0-0">
                                        <div className="sela_platform-construction_of_borehole-0">
                                            Construction of Borehole
                                        </div>
                                        <div className="sela_platform-budget_5">
                                            {"Budget: $50,000.00"}
                                        </div>
                                        <div className="sela_platform-ikorodu_lagos-0">
                                            {"Ikorodu, Lagos"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-4" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-2" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-0-0-0-1-1">
                            <div className="sela_platform-0-0-0-1-1-0">
                                <div className="sela_platform-0-0-0-1-1-0-0">
                                    <div className="sela_platform-0-0-0-1-1-0-0-0">
                                        <div className="sela_platform-the_people_of_ikorodu_have_long_sought_for_a_solution_to_the_perennial_water_crisis_plaguing_the_community_help_came_when_community_members_took_action_and_decided_to_solve_the_problem_read_more-0">
                                            <div>The people of Ikorodu have long sought for a solution </div>
                                            <div>{"to the perennial water crisis plaguing the community. "}</div>
                                            <div>Help came when community members took action</div>
                                            <div>{"and decided to solve the problem...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-0">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-0">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/b75a/b760/d46ae0905cd26e08d340528ddea5f163" className="sela_platform-image-6" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/0cb2/03f0/01fda77bcf46ea48f454a771ce01a3fd" className="sela_platform-image-1" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-19" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="sela_platform-card-00">
                <div className="sela_platform-0-1-0">
                    <div className="sela_platform-image-9">
                        <div className="sela_platform-0-1-0-0-0">
                            <div className="sela_platform-image_mask-00">
                                <div className="sela_platform-0-1-0-0-0-0-0">
                                    <div className="sela_platform-0-1-0-0-0-0-0-0">
                                        <div className="sela_platform-0-1-0-0-0-0-0-0-0">
                                            <div className="sela_platform-0-1-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-on_track_to_be_defaulted-0">
                                                    On track to be defaulted
                                                </div>
                                                <div className="sela_platform-rectangle_4_" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-0-1-0-0-0-0-1">
                                    <div className="sela_platform-0-1-0-0-0-0-1-0">
                                        <div className="sela_platform-0-1-0-0-0-0-1-0-0">
                                            <div className="sela_platform-0-1-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_bar-00" /> 
                                                <div className="sela_platform-0_">{"0% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-0-1-0-1">
                        <div className="sela_platform-0-1-0-1-0">
                            <div className="sela_platform-0-1-0-1-0-0">
                                <div className="sela_platform-0-1-0-1-0-0-0">
                                    <div className="sela_platform-0-1-0-1-0-0-0-0">
                                        <div className="sela_platform-renovation_of_classrooms-0">
                                            Renovation of Classrooms
                                        </div>
                                        <div className="sela_platform-budget_5_">
                                            {"Budget: $5,000.00"}
                                        </div>
                                        <div className="sela_platform-benin_city_edo-0">
                                            {"Benin City, Edo"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-95" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-79" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-0-1-0-1-1">
                            <div className="sela_platform-0-1-0-1-1-0">
                                <div className="sela_platform-0-1-0-1-1-0-0">
                                    <div className="sela_platform-0-1-0-1-1-0-0-0">
                                        <div className="sela_platform-education_remains_the_only_sure_way_to_guarantee_the_future_of_the_next_generation_this_project_is_expected_to_change_the_poor_educational_facilities_that_have_made_it_difficult_for_students_read_more-0">
                                            <div>Education remains the only sure way to guarantee </div>
                                            <div>{"the future of the next generation. This project is"}</div>
                                            <div>expected to change the poor educational facilities</div>
                                            <div>{"that have made it difficult for students...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-00">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-00">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/9f78/83c5/76b097b3b4da4e07dea760790e5310f3" className="sela_platform-image-97" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/f84c/7892/01ea886ce574c79e0f17e15129ab4b56" className="sela_platform-image-8" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/6c5f/6727/62d994ec0de8c1fc27b7d5eefd36438e" className="sela_platform-image-61" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-27" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="sela_platform-1">
            <div className="sela_platform-card-000">
                <div className="sela_platform-1-0-0">
                    <div className="sela_platform-image-91">
                        <div className="sela_platform-1-0-0-0-0">
                            <div className="sela_platform-image_mask-000">
                                <div className="sela_platform-1-0-0-0-0-0-0">
                                    <div className="sela_platform-1-0-0-0-0-0-0-0">
                                        <div className="sela_platform-1-0-0-0-0-0-0-0-0">
                                            <div className="sela_platform-1-0-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-rectangle_4_4" /> 
                                                <div className="sela_platform-completed-0">Completed</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-1-0-0-0-0-0-1">
                                    <div className="sela_platform-1-0-0-0-0-0-1-0">
                                        <div className="sela_platform-1-0-0-0-0-0-1-0-0">
                                            <div className="sela_platform-1-0-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_indicator-00">
                                                    <div className="sela_platform-1-0-0-0-0-0-1-0-0-0-0-0">
                                                        <div className="sela_platform-progress_bar-000" /> 
                                                    </div>
                                                </div>
                                                <div className="sela_platform-10">{"100% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-1-0-0-1">
                        <div className="sela_platform-1-0-0-1-0">
                            <div className="sela_platform-1-0-0-1-0-0">
                                <div className="sela_platform-1-0-0-1-0-0-0">
                                    <div className="sela_platform-1-0-0-1-0-0-0-0">
                                        <div className="sela_platform-rebuilding_the_tema_bridge-0">
                                            Rebuilding the Tema Bridge
                                        </div>
                                        <div className="sela_platform-budget_7">
                                            {"Budget: $70,000.00"}
                                        </div>
                                        <div className="sela_platform-gold_coast_ghana-0">
                                            {"Gold Coast, Ghana"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-12" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-0" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-1-0-0-1-1">
                            <div className="sela_platform-1-0-0-1-1-0">
                                <div className="sela_platform-1-0-0-1-1-0-0">
                                    <div className="sela_platform-1-0-0-1-1-0-0-0">
                                        <div className="sela_platform-this_project_involves_the_rebuilding_of_the_tema_bridge_which_was_destroyed_by_erosion_in_2">
                                            <div>This project involves the rebuilding of the Tema bridge </div>
                                            <div>{"which was destroyed by erosion in 2014. Contractors"}</div>
                                            <div>submitted bids and went through a competitive series</div>
                                            <div>{"of steps before they were selected...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-000">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-000">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/5652/2651/b62bf404b927e53cf9f91c4b6b8a4220" className="sela_platform-image-96" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/329c/685c/6e8f38a2199b927b3ba77fe0bad6aac9" className="sela_platform-image-86" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/04e7/e88f/b233285d2995d8be69158243d61f437b" className="sela_platform-image-09" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-87" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="sela_platform-card-0000">
                <div className="sela_platform-1-1-0">
                    <div className="sela_platform-image-71">
                        <div className="sela_platform-1-1-0-0-0">
                            <div className="sela_platform-image_mask-0000">
                                <div className="sela_platform-1-1-0-0-0-0-0">
                                    <div className="sela_platform-1-1-0-0-0-0-0-0">
                                        <div className="sela_platform-1-1-0-0-0-0-0-0-0">
                                            <div className="sela_platform-1-1-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-rectangle_4_4-0" /> 
                                                <div className="sela_platform-defaulted-0">Defaulted</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-1-1-0-0-0-0-1">
                                    <div className="sela_platform-1-1-0-0-0-0-1-0">
                                        <div className="sela_platform-1-1-0-0-0-0-1-0-0">
                                            <div className="sela_platform-1-1-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_bar-0000">
                                                    <div className="sela_platform-1-1-0-0-0-0-1-0-0-0-0-0">
                                                        <div className="sela_platform-progress_indicator-000" /> 
                                                    </div>
                                                </div>
                                                <div className="sela_platform-2_">{"2% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-1-1-0-1">
                        <div className="sela_platform-1-1-0-1-0">
                            <div className="sela_platform-1-1-0-1-0-0">
                                <div className="sela_platform-1-1-0-1-0-0-0">
                                    <div className="sela_platform-1-1-0-1-0-0-0-0">
                                        <div className="sela_platform-repair_of_eroded_road-0">
                                            Repair of Eroded Road
                                        </div>
                                        <div className="sela_platform-budget_5_0">
                                            {"Budget: $5,000.00"}
                                        </div>
                                        <div className="sela_platform-yenagoa_bayelsa-0">
                                            {"Yenagoa, Bayelsa"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-69" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-65" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-1-1-0-1-1">
                            <div className="sela_platform-1-1-0-1-1-0">
                                <div className="sela_platform-1-1-0-1-1-0-0">
                                    <div className="sela_platform-1-1-0-1-1-0-0-0">
                                        <div className="sela_platform-this_project_will_involve_the_repair_of_the_yenagoa_road_destroyed_due_to_the_impact_of_erosion_it_will_be_done_within_the_dry_season_of_the_year_to_ensure_the_work_is_not_interrupted_by_the_rains_read_more-0">
                                            <div>This project will involve the repair of the Yenagoa road</div>
                                            <div>{"destroyed due to the impact of erosion. It will be done"}</div>
                                            <div>within the dry season of the year to ensure the work</div>
                                            <div>{"is not interrupted by the rains...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-0000">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-0000">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/bc7d/cabf/eb65e37c17ced52c3043d692869ed033" className="sela_platform-image-47" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2b2c/3c5d/b5f0a5987960abbf6f48971332c1876e" className="sela_platform-image-13" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-78" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="sela_platform-2">
            <div className="sela_platform-card-00000">
                <div className="sela_platform-2-0-0">
                    <div className="sela_platform-image-25">
                        <div className="sela_platform-2-0-0-0-0">
                            <div className="sela_platform-image_mask-00000">
                                <div className="sela_platform-2-0-0-0-0-0-0">
                                    <div className="sela_platform-2-0-0-0-0-0-0-0">
                                        <div className="sela_platform-2-0-0-0-0-0-0-0-0">
                                            <div className="sela_platform-2-0-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-rectangle_4_4-00" /> 
                                                <div className="sela_platform-not_initiated-0">
                                                    Not Initiated
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-2-0-0-0-0-0-1">
                                    <div className="sela_platform-2-0-0-0-0-0-1-0">
                                        <div className="sela_platform-2-0-0-0-0-0-1-0-0">
                                            <div className="sela_platform-2-0-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_bar-00000" /> 
                                                <div className="sela_platform-0_c">{"0% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-2-0-0-1">
                        <div className="sela_platform-2-0-0-1-0">
                            <div className="sela_platform-2-0-0-1-0-0">
                                <div className="sela_platform-2-0-0-1-0-0-0">
                                    <div className="sela_platform-2-0-0-1-0-0-0-0">
                                        <div className="sela_platform-construction_of_health_center-0">
                                            Construction of Health Center
                                        </div>
                                        <div className="sela_platform-budget_55">
                                            {"Budget: $55,000.00"}
                                        </div>
                                        <div className="sela_platform-jos_plateau-0">
                                            {"Jos, Plateau"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-94" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-3" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-2-0-0-1-1">
                            <div className="sela_platform-2-0-0-1-1-0">
                                <div className="sela_platform-2-0-0-1-1-0-0">
                                    <div className="sela_platform-2-0-0-1-1-0-0-0">
                                        <div className="sela_platform-this_proposed_health_care_facility_will_providethe_much_needed_health_care_for_the_people_of_this_commuity_and_is_expected_to_go_a_long_way_in_solving_the_infant_mortality_problem_read_more-0">
                                            <div>This proposed health care facility will providethe much</div>
                                            <div>{"needed health care for the people of this commuity,"}</div>
                                            <div>and is expected to go a long way in solving the infant</div>
                                            <div>{"mortality problem...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-00000">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-00000">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/d390/27a8/d7090d91cdba40f721052c943db6dbea" className="sela_platform-image-76" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/a75b/dd38/cdea0ea41be29aec52d5068e76a42bf5" className="sela_platform-image-67" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/daab/eaee/31df9a0c0f3b05bd164929348f5e73e4" className="sela_platform-image-5" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-672" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="sela_platform-card-000004">
                <div className="sela_platform-2-1-0">
                    <div className="sela_platform-image-24">
                        <div className="sela_platform-2-1-0-0-0">
                            <div className="sela_platform-image_mask-000000">
                                <div className="sela_platform-2-1-0-0-0-0-0">
                                    <div className="sela_platform-2-1-0-0-0-0-0-0">
                                        <div className="sela_platform-2-1-0-0-0-0-0-0-0">
                                            <div className="sela_platform-2-1-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-rectangle_4_4-000" /> 
                                                <div className="sela_platform-completed-00">Completed</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-2-1-0-0-0-0-1">
                                    <div className="sela_platform-2-1-0-0-0-0-1-0">
                                        <div className="sela_platform-2-1-0-0-0-0-1-0-0">
                                            <div className="sela_platform-2-1-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_bar-000002">
                                                    <div className="sela_platform-2-1-0-0-0-0-1-0-0-0-0-0">
                                                        <div className="sela_platform-progress_indicator-0000" /> 
                                                    </div>
                                                </div>
                                                <div className="sela_platform-100">{"100% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-2-1-0-1">
                        <div className="sela_platform-2-1-0-1-0">
                            <div className="sela_platform-2-1-0-1-0-0">
                                <div className="sela_platform-2-1-0-1-0-0-0">
                                    <div className="sela_platform-2-1-0-1-0-0-0-0">
                                        <div className="sela_platform-construction_of_udala_road-0">
                                            Construction of Udala Road
                                        </div>
                                        <div className="sela_platform-budget_1">
                                            {"Budget: $15,000.00"}
                                        </div>
                                        <div className="sela_platform-mile_2">
                                            {"Mile 2, Nnewi"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-698" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-66" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-2-1-0-1-1">
                            <div className="sela_platform-2-1-0-1-1-0">
                                <div className="sela_platform-2-1-0-1-1-0-0">
                                    <div className="sela_platform-2-1-0-1-1-0-0-0">
                                        <div className="sela_platform-the_udala_road_links_seven_commuities_and_is_a_major_market_route_for_buyers_and_sellers_of_farm_produce_the_project_is_aimed_at_making_this_road_motorable_to_enhance_trade_and_commerce_in_the_area_read_more-0">
                                            <div>The Udala road links seven commuities and is a major</div>
                                            <div>{"market route for buyers and sellers of farm produce."}</div>
                                            <div>The project is aimed at making this road motorable to</div>
                                            <div>{"enhance trade and commerce in the area...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-000002">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-000000">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/04e7/e88f/b233285d2995d8be69158243d61f437b" className="sela_platform-image-83" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/50ea/16e2/d4f9939350e95ac3a43cb7783bdbe19a" className="sela_platform-image-42" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-867" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="sela_platform-3">
            <div className="sela_platform-card-000002">
                <div className="sela_platform-3-0-0">
                    <div className="sela_platform-image-50">
                        <div className="sela_platform-3-0-0-0-0">
                            <div className="sela_platform-image_mask-000003">
                                <div className="sela_platform-3-0-0-0-0-0-0">
                                    <div className="sela_platform-3-0-0-0-0-0-0-0">
                                        <div className="sela_platform-3-0-0-0-0-0-0-0-0">
                                            <div className="sela_platform-3-0-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-rectangle_4_4-0000" /> 
                                                <div className="sela_platform-completed-000">
                                                    Completed
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-3-0-0-0-0-0-1">
                                    <div className="sela_platform-3-0-0-0-0-0-1-0">
                                        <div className="sela_platform-3-0-0-0-0-0-1-0-0">
                                            <div className="sela_platform-3-0-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_indicator-00000">
                                                    <div className="sela_platform-3-0-0-0-0-0-1-0-0-0-0-0">
                                                        <div className="sela_platform-progress_bar-000001" /> 
                                                    </div>
                                                </div>
                                                <div className="sela_platform-100_">{"100% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-3-0-0-1">
                        <div className="sela_platform-3-0-0-1-0">
                            <div className="sela_platform-3-0-0-1-0-0">
                                <div className="sela_platform-3-0-0-1-0-0-0">
                                    <div className="sela_platform-3-0-0-1-0-0-0-0">
                                        <div className="sela_platform-construction_of_classroom-0">
                                            Construction of Classroom
                                        </div>
                                        <div className="sela_platform-budget_8">
                                            {"Budget: $80,000.00"}
                                        </div>
                                        <div className="sela_platform-sambisa_borno-0">
                                            {"Sambisa, Borno"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-89" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-36" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-3-0-0-1-1">
                            <div className="sela_platform-3-0-0-1-1-0">
                                <div className="sela_platform-3-0-0-1-1-0-0">
                                    <div className="sela_platform-3-0-0-1-1-0-0-0">
                                        <div className="sela_platform-the_boko_haram_scourge_led_to_the_destruction_of_this_classroom_which_has_now_been_fully_rebuilt_and_equipped_with_state_of_the_art_facilities_to_aid_the_learning_of_students_read_more-0">
                                            <div>The Boko Haram scourge led to the destruction of</div>
                                            <div>this classroom which has now been fully rebuilt and</div>
                                            <div>equipped with state of the art facilities to aid the</div>
                                            <div>{"learning of students...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-0000023">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-000003">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/ffb2/b5ea/c80caf8f23a7afea92d5c559cc379b7b" className="sela_platform-image-37" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/50ea/16e2/d4f9939350e95ac3a43cb7783bdbe19a" className="sela_platform-image-30" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/b75a/b760/d46ae0905cd26e08d340528ddea5f163" className="sela_platform-image-20" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-56" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="sela_platform-card-0000027">
                <div className="sela_platform-3-1-0">
                    <div className="sela_platform-image-62">
                        <div className="sela_platform-3-1-0-0-0">
                            <div className="sela_platform-image_mask-000002">
                                <div className="sela_platform-3-1-0-0-0-0-0">
                                    <div className="sela_platform-3-1-0-0-0-0-0-0">
                                        <div className="sela_platform-3-1-0-0-0-0-0-0-0">
                                            <div className="sela_platform-3-1-0-0-0-0-0-0-0-0">
                                                <div className="sela_platform-on_track_to_be_completed-0">
                                                    On track to be completed
                                                </div>
                                                <div className="sela_platform-rectangle_4_4-00000" /> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="sela_platform-3-1-0-0-0-0-1">
                                    <div className="sela_platform-3-1-0-0-0-0-1-0">
                                        <div className="sela_platform-3-1-0-0-0-0-1-0-0">
                                            <div className="sela_platform-3-1-0-0-0-0-1-0-0-0">
                                                <div className="sela_platform-progress_bar-0000010">
                                                    <div className="sela_platform-3-1-0-0-0-0-1-0-0-0-0-0">
                                                        <div className="sela_platform-progress_indicator-000001" /> 
                                                    </div>
                                                </div>
                                                <div className="sela_platform-8">{"80% complete"}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="sela_platform-3-1-0-1">
                        <div className="sela_platform-3-1-0-1-0">
                            <div className="sela_platform-3-1-0-1-0-0">
                                <div className="sela_platform-3-1-0-1-0-0-0">
                                    <div className="sela_platform-3-1-0-1-0-0-0-0">
                                        <div className="sela_platform-construction_of_burna_bridge-0">
                                            Construction of Burna Bridge
                                        </div>
                                        <div className="sela_platform-budget_10">
                                            {"Budget: $10,000.00"}
                                        </div>
                                        <div className="sela_platform-minna_niger-0">
                                            {"Minna, Niger"}
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/801b/23d3/fb15c96d6db44132ec41cfae57537ea1" className="sela_platform-image-711" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/fc81/8403/5d61b465ccccd5cbe3f52dfbeef0d3dc" className="sela_platform-image-693" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="sela_platform-3-1-0-1-1">
                            <div className="sela_platform-3-1-0-1-1-0">
                                <div className="sela_platform-3-1-0-1-1-0-0">
                                    <div className="sela_platform-3-1-0-1-1-0-0-0">
                                        <div className="sela_platform-the_burna_bridge_project_will_link_eight_communities_and_aid_the_inflow_of_essential_goods_and_services_to_these_areas_it_is_expected_to_be_completed_in_the_next_two_months_read_more-0">
                                            <div>The Burna Bridge project will link eight communities</div>
                                            <div>and aid the inflow of essential goods and services to</div>
                                            <div>{"these areas. It is expected to be completed in the "}</div>
                                            <div>{"next two months...Read more "}</div>
                                        </div>
                                        <div className="sela_platform-view_more_details-000001">
                                            View more details
                                        </div>
                                        <div className="sela_platform-contractors-000001">
                                            Contractors
                                        </div>
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/0cb2/03f0/01fda77bcf46ea48f454a771ce01a3fd" className="sela_platform-image-77" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/9ae5/7b7d/9910354414cbe350b890531b478fe6eb" className="sela_platform-image-11" /> 
                                        <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2d85/8c45/2fc2ee9e62e22b12cf52d0d0a98444f8" className="sela_platform-image-33" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="sela_platform-4">
            <div className="sela_platform-4-0">
                <div className="sela_platform-4-0-0">
                    <div className="sela_platform-ellipse-0" /> 
                </div>
            </div>
            <div className="sela_platform-4-1">
                <div className="sela_platform-4-1-0">
                    <div className="sela_platform-ellipse-00" /> 
                </div>
            </div>
            <div className="sela_platform-4-2">
                <div className="sela_platform-4-2-0">
                    <div className="sela_platform-ellipse-000" /> 
                </div>
            </div>
            <div className="sela_platform-4-3">
                <div className="sela_platform-4-3-0">
                    <div className="sela_platform-ellipse-0000" /> 
                </div>
            </div>
            <div className="sela_platform-4-4">
                <div className="sela_platform-4-4-0">
                    <div className="sela_platform-ellipse-00000" /> 
                </div>
            </div>
            <div className="sela_platform-ellipse-000004" /> 
        </div>
        <div className="sela_platform-5">
            <div className="sela_platform-_c_sela_2">
                {"(c) Sela. 2018"}
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}