export default {
  FETCH_PROJECTS_IN_PROGRESS: "FETCH_PROJECTS_IN_PROGRESS",
  FETCH_PROJECTS_SUCCESSFUL: "FETCH_PROJECTS_SUCCESSFUL",
  FETCH_PROJECTS_FAILED: "FETCH_PROJECTS_FAILED",

  FETCH_ALL_PROJECTS_DATA_FOR_MAPS_IN_PROGRESS: "FETCH_ALL_PROJECTS_DATA_FOR_MAPS_IN_PROGRESS",
  FETCH_ALL_PROJECTS_DATA_FOR_MAPS_SUCCESSFUL: "FETCH_ALL_PROJECTS_DATA_FOR_MAPS_SUCCESSFUL",
  FETCH_ALL_PROJECTS_DATA_FOR_MAPS_FAILED: "FETCH_ALL_PROJECTS_DATA_FOR_MAPS_FAILED",

  ADD_PROJECT_IN_PROGRESS: "ADD_PROJECT_IN_PROGRESS",
  ADD_PROJECT_SUCCESSFUL: "ADD_PROJECT_SUCCESSFUL",
  ADD_PROJECT_FAILED: "ADD_PROJECT_FAILED"
};
