export default {

    FETCH_PROJECTS_IN_PROGRESS: "FETCH_PROJECTS_IN_PROGRESS",
    FETCH_PROJECTS_SUCCESSFUL: "FETCH_PROJECTS_SUCCESSFUL",
    FETCH_PROJECTS_FAILED: "FETCH_PROJECTS_FAILED",

    ADD_PROJECT_IN_PROGRESS: "ADD_PROJECT_IN_PROGRESS",
    ADD_PROJECT_SUCCESSFUL: "ADD_PROJECT_SUCCESSFUL",
    ADD_PROJECT_FAILED: "ADD_PROJECT_FAILED",
    

    
}